HyperBackgroundNoise:
  noise_scale:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.1
HyperImageSky:
  sky_scale:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -1.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.1
