adaptive_brightness.AdaptiveBrightness:
  inner_coefficient:
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
  outer_coefficient:
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
  signal_scale:
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
constant.Constant:
  coefficient:
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
constant_zeorth.ConstantZeroth:
  coefficient_neighbor:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
  coefficient_zeroth:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
